# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thug's Rumal
email: dennis.parchkov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thug is a tool for studying exploit kits by emulating a web browser.
  Information extracted can aid in determining if a web page is malicious.
  Rumal was developed  to provide a web GUI for thug allowing the visualiszation
  of Thug's analysis.
  This website provides usefull information about the development of Rumal plus any updates we have on it. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  Dennisparchkov

# Build settings
markdown: kramdown
name: Thugs Rumal 
